### ISSUE TITLE
Excellapis JAR missing

### ISSUE THREAD

**Issue by arana3** [excell-mobility/routing_service#5]
I think issue is similar to scheduling-service [#7](https://github.com/excell-mobility/scheduling_service/issues/7).

There is missing dependency in relation to the excellapis snapshot JAR, causing compilation errors on the controller and elsewhere. Is this going to be published or does it require an email exchange?

Regards,
Ahmad

**Comment by FxKu** [comment]
Indeed, it's the same issue. I'm still looking for a clever way how to deal with this dependency and its config parameters. But, if you are interested in using only the routing service, my current idea would still be too complicated. I let you know, when I have solution ready to test.

What you can already do is to register [here](excell-mobility.com/developer) and use the online web-services. It's free. But, routing only works for germany, currently.

**Comment by arana3** [comment]
Thanks FxKu. 

I'm curious to know the design decision made to have a utility to get near realtime travel times. If the weightings can be done without knowing current travel times for a route (via the TravelTimeWrapper), then the routing service can provide routes purely in an offline fashion.

This could eliminate the need for Excellapis JAR directly in the routing service. Spring's IoC and interface(s) could be utilized to inject the necessary wrapper components without causing compile time issues. If user needs realtime travel times, then they will would need the Excellapis dependency for proper runtime execution.

**Comment by FxKu** [comment]
I'm happy to inform you, that I was able to exclude the excellapis dependency. There are a few more parameters to adjust in the `application.properties` file. You can specify the URL to the [TravelTimeService](https://github.com/excell-mobility/TravelTimeService), but you can also choose to not use it at all. Travel times work only for Dresden at the moment and you would need the same graph used by the service. I added some comments to the README.

**Comment by arana3** [comment]
This is awesome! Will start taking a look and play around.
